#!/bin/bash

# use ff <search terms> to open firefox with the query

# Example:
#    ff stewart calculus


if [ -z "$1" ]; then
    # echo "No argument supplied"
    firefox 
else
    # combine search terms with +
    local IFS='+'
    firefox "http://www.google.com/search?q=${*}"
fi
